# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1STKswsp-6Xwml7qJn5jibJXtUJswe4LZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train.csv',index_col=0)

gender=pd.get_dummies(df['Gender'],drop_first=True)
vehicle_age=pd.get_dummies(df['Vehicle_Age'],drop_first=True)
vehicle_damage=pd.get_dummies(df['Vehicle_Damage'],drop_first=True)

df.drop(['Gender','Vehicle_Age','Vehicle_Damage'],axis=1,inplace=True)

df=pd.concat([df,gender,vehicle_age,vehicle_damage],axis=1)

x=df.drop(['Response'],axis=1)

y=df['Response']

y.head()

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.30,random_state=10)

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

from sklearn.neighbors import  KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=1)

knn.fit(xtrain,ytrain)

ypred=knn.predict(xtest)

from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

error_rate = []

# Will take some time
for i in range(1,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(xtrain,ytrain)
    pred_i = knn.predict(xtest)
    error_rate.append(np.mean(pred_i != ytest))

plt.Figure(figsize=(20,8))
plt.plot(range(1,40),error_rate,color='blue',linestyle='dashed',marker='o',markerfacecolor='red',markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')

knn=KNeighborsClassifier(n_neighbors=20)

knn.fit(xtrain,ytrain)

Ypred=knn.predict(xtest)

print(confusion_matrix(ytest,Ypred))
print(classification_report(ytest,Ypred))

